### ISSUE TITLE
LRU Option

### ISSUE THREAD

**Issue by jpodwys** [ptarjan/node-cache#34]
I've been using node-cache for nearly a year now and I really appreciate it. I was wondering if you might be interested in adding an LRU option. I would love to be able to have confidence that node-cache will not use more memory I want it to. 

To be clear, I'm not talking about limiting the number of keys, but the number of bytes. 

What are your thoughts?

**Comment by ptarjan** [comment]
It seems like it might be better as a layer above `node-cache`. There isn't anything in the caching layer that inspects the data it is storing, so adding runtime overhead on stores for sizes seems bad. And putting a switch to turn on LRU feels like it would be just a complete separate code path.
