### ISSUE TITLE
.put() return value

### ISSUE THREAD

**Issue by lukehorvat** [ptarjan/node-cache#45]
Could we make `.put()` return the value being cached?

I'm using this module to cache the responses of a small Express app, and I've found that I seem to employ the following pattern a lot:

```javascript
let data = [1, 2, 3, 4];
cache.put(key, data);
response.send(data);
```

It would be nice if you could do something like the following, so I don't need to have a separate caching step and `data` variable:

```javascript
response.send(cache.put(key, [1, 2, 3, 4]));
```

Plus, it would also make it similar to object literal assignment:

```javascript
obj[key] = value; // Returns value.
```

**Comment by ptarjan** [comment]
That's sounds reasonable. I'd accept a PR.
