### ISSUE TITLE
Cache.get returns reference to object rather than copy of object

### ISSUE THREAD

**Issue by brianchaan** [ptarjan/node-cache#53]
If you use cache.get to retrieve an object from the cache, and then you extend the object that you retrieved with other variables, the underlying cache gets updated without needing to call cache.put. For example:

> var a = cache.get('a')
 a.user = 'Some Guy';
 a.private = 'personal information for Some Guy';
 // the cached version of _a_ now has .user and .private

cache.get should return a deep copy of the object, or you can run into some very confusing use cases without realizing it.

**Comment by ptarjan** [comment]
There are many unclonable things in javascript, like functions, DOM nodes, Maps, Sets, and WeakMaps. How should I deal with those? Also, how deep do I clone?

**Comment by colinangusmackay** [comment]
Personally, I would expect a reference to the object in the cache rather than a copy of it when retrieving it. If you want a copy why not just copy on retrieval.

**Comment by joeycozza** [comment]
I agree with @colinangusmackay . Return the reference, and allow the user to use lodash's cloneDeep() or something if they'd rather have a copy. Maybe you could explicitly put in the README that .get() returns a reference, and not a copy.

**Comment by bherila** [comment]
I also agree with @colinangusmackay

**Comment by ptarjan** [comment]
Closing out as this semantic seems counter-intuitive.
