### ISSUE TITLE
How big is memory-cache?

### ISSUE THREAD

**Issue by MegazeroMZ** [ptarjan/node-cache#54]
I was wondering if there's anyway we can know how much memory will memory-cache took? can we limit/control it somehow? Will the performance goes down if the size of memory-cache is too big?

**Comment by ptarjan** [comment]
calling `.size()` will tell you the number of entries. If you want size limits I would put a layer in front that does the bookkeeping for you.

**Comment by MegazeroMZ** [comment]
I dont mean the number of entries, I mean size in term of KB or so, is there anyway to get that data?

**Comment by ptarjan** [comment]
I'd be open to a debugging option if you want to add it.
