### ISSUE TITLE
Issue in cluster environment

### ISSUE THREAD

**Issue by ravisoni6262** [ptarjan/node-cache#69]
When run our node module in cluster environment each cluster creates its own cache instance in memory. This is not acceptable module should have the capability to share same cache instance within multiple clusters.

I'm using pm2 : process manager for cluster.

Any development on this?

**Comment by soyuka** [comment]
You can't share memory between sub processes like this.

**Comment by ptarjan** [comment]
You're going to have a do something at a higher level than this library if you want IPC.

**Comment by brandonros** [comment]
@soyuka @ptarjan Can you share any ideas? The main reason I use this library (node-cache) is to avoid JSON.parse + JSON.stringify (expensive in my situation).

I've thought of IPC and redis, but I only moved to this package from those because of that...

**Comment by ptarjan** [comment]
You have an architecture problem not a code one. Either you want a out of process cache where you will have to serialize and deserialize somehow or you want an in-process cache which this library is. If your serialization is slow then maybe try a different serialization format like Thrift or Protobuff.

**Comment by soyuka** [comment]
@brandonros depends what you want to share, IPC is using strings, and is JSON stringifying (used EventEmitter on top of IPC [here](https://github.com/soyuka/IPCEE) and I'm explaining it shortly). 

I also wrote a [blog article](https://soyuka.me/having-fun-with-nodejs-child-processes/) about a [module](https://github.com/soyuka/relieve) that helps managing micro services, maybe you can look at that too.

You can use redis too, I'm using [subscribe](http://redis.io/commands/subscribe) amongst lists to communicate between services and store some cached data. I try to avoid `JSON.stringify`, and if you use it with redis, you may do things wrong [another blog post about indexing a hash with a set](https://soyuka.me/indexing-hashes-with-a-set-in-redis/). Anyway, `JSON.stringify` might not be that slow, depends mainly on the nesting of objects. As @ptarjan said you can look at other serialization ways, (msgpack, igbinary etc.).

**Comment by arnavyagnikoyo** [comment]
I have my server running on multiple instances and from my understanding every instance will have its own copies, how we can go and clear every instance's cache . what could be the way?
