### ISSUE TITLE
nodeunit tests wait for the timeout function to finish

### ISSUE THREAD

**Issue by JoeZ99** [ptarjan/node-cache#7]
I'm not very sure if this can be considered "an issue".

Running the following test with nodeunit

````javascript
exports['ttt'] =
    nodeunit.testCase(
        {
         test: function(test) {
             var cache = require('memory-cache');
             cache.put('key', 'value', 1000000);
             test.ok(true);
             test.done();
         }
        }
    );
````

won't show back the prompt until the cache has deleted the key, which is after 1000000 ms passed.

Shouldn't it be better if, instead of using a setTimeout function to delete the key, the absolute timeout parameter were saved with the key and then when trying to access it with get, ````if (time() > timeout) return null;````

**Comment by ptarjan** [comment]
`clear` now does all the `clearTimeout`s
