### ISSUE TITLE
max memory limit

### ISSUE THREAD

**Issue by antonioaltamura** [ptarjan/node-cache#77]
Hi, what do you think about add this feature?
I mean just a simple way to control the cache grown.

**Comment by ptarjan** [comment]
This library isn't for volatile caches. If it was I would have written it in a way where every key knew how to populate itself and would just use the cache when RAM was available. Instead it is very much for persistant on-box caching.

If you are worried about memory limits, I'd recommend using `performance.memory` APIs and then doing things that are specific to your application on how to limit memory growth.

**Comment by antonioaltamura** [comment]
don't you think an unlimited hashmap growth may be also a security flaw?
What's happen if I intentionally make thousands of different request and let the hashmap grows in the order of magnitude of hundreds of MB in little time?
