### ISSUE TITLE
How this module is different from storing data directly in variables

### ISSUE THREAD

**Issue by lel1234** [ptarjan/node-cache#78]
I'm just wondering if this module do more than simply storing data in variables? Does it resolve some conflicts? Or does it have a better response time or something ?

Thanks!

**Comment by paolo-tanium** [comment]
Variables lose scope after you exit the function they were declared from. This is persistent until the ttl.

**Comment by gswalden** [comment]
Adds some useful utilities (ability to automatically expire, hit counts) as well.

**Comment by lel1234** [comment]
Okay thanks!
