### ISSUE TITLE
Does it auto clean

### ISSUE THREAD

**Issue by puppetmaster3** [ptarjan/node-cache#86]
It says it will clear cache on get.

So if I have a million things and never get, they stay in ram don't timeout?

**Comment by dvidsilva** [comment]
A value on a key will get removed if you try to access it after its expiration, or when it's expiration is reached. But if you set no expiration or set too many values it will eat your ram.

**Comment by ptarjan** [comment]
If you set a timeout for your keys, they will be purged from your RAM after that timeout value is hit. https://github.com/ptarjan/node-cache/blob/master/index.js#L34
