### ISSUE TITLE
.get() for cached MongoDB data with Date() objects strips Date() of its methods

### ISSUE THREAD

**Issue by roctimo** [ptarjan/node-cache#9]
Attempted to call a native date function on a Date object from some cached MongoDB data, and received this error:

    TypeError: Object 00:04:23 has no method 'getHours'

In my code, first the MongoDB query runs and displays the data fine, and then on reload it uses the cached raw data, and throws this error when it tries to run getHours on the cached Date object.

**Comment by ptarjan** [comment]
There is no serialization involved, so you get the same object back. I doubt the problem is in this library.
